#!/bin/bash

sdate=${1}
tdate=`date +"%m/%d/%y"`
cdate=`date +"%y%m%d"`
rdir=`pwd`
logdir=$MK_CHANGELOG_PATH
if ["$MK_CHANGELOG_PATH" = ""]; then
logdir=`pwd`
fi

rm -f $logdir/Changelog_$cdate.log

clear

# Check the date start range is set
if [ -z "$sdate" ]; then
echo""
echo "ATTENTION: Start date not defined ----------------------------------------------------"
    echo""
    echo " >>> Please define a start date in mm/dd/yyyy format ..."
    echo""
    echo "----------------------------------------------------------------------------------"
    read sdate
fi

# Find the directories to log
echo"";echo"";echo""
echo "MoKee OpenSource Changelog -------------------"
echo""
# Log starter
echo "MoKee OpenSource Changelog from $sdate" - "$tdate" >> "$logdir"/Changelog_$cdate.log
echo "---------------------------------------------------------------" >> "$logdir"/Changelog_$cdate.log
echo " " >> "$logdir"/Changelog_$cdate.log
find -name .git | sed 's/\/.git//g' | sed 'N;$!P;$!D;$d' | while read line
do
cd $line
    # Test to see if the repo needs to have a changelog written.
    log=$(git log --pretty="%an - %s" --no-merges --since=$sdate --date-order)
    # Forgive my bad script :P
    project=${line#*/}
    if [ ! -z "$log" ]; then
        # Write the changelog
        echo " >>> Changelog is updated and written for $project ..."
        echo "Project: $project" >> "$logdir"/Changelog_$cdate.log
        echo "$log" | while read line
        do
echo " $line" >> "$logdir"/Changelog_$cdate.log
        done
echo "" >> "$logdir"/Changelog_$cdate.log
    fi
cd $ANDROID_BUILD_TOP
done
echo""
echo "-------------------------------------------------"
echo"";echo"";echo""
