#!/bin/bash
#
# Copyright (C) 2013 The MoKee OpenSource Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

INPUT=$MK_OTA_INPUT/$MK_BUILDTYPE/$MK_BUILD
OUTPUT=out/target/OTA/$MK_BUILD
LOGDIR=$OUTPUT/logs

cp out/target/product/$MK_BUILD/MK*${MK_BUILDTYPE}.zip $INPUT
build/tools/mk_ota_script/ota $INPUT $OUTPUT $LOGDIR

if [ ! -z "$MK_OTA_EXTRA" ];then
	cp $OUTPUT/* $MK_OTA_EXTRA
fi