#!/bin/bash
#
# Copyright (C) 2013 The MoKee OpenSource Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ -z "`which xdelta3 2> /dev/null`" ];then
        echo "xdelta3 is not installed!"
        echo "Please install it first!"
        exit 1
elif [ -z "$MK_OTA_INPUT" ];then
	echo "MK_OTA_INPUT not defined!"
	exit 1
elif [ -z "$1" ];then
	echo "No argument given! [RELEASE/NIGHTLY/EXPERIMENTAL/UNOFFICIAL]"
	exit 1
else
	TYPE=$1
	INPUT=$MK_OTA_INPUT/$TYPE
fi

if [ -z "$OUT_DIR" ];then
	OUTPUT=out/target/OTA/$TYPE
else
	OUTPUT=$OUT_DIR/target/OTA/$TYPE
fi
LOGDIR=$OUTPUT/logs

if [ ! -z "$2" ];then
	TARGET=`echo $2 | tr "," " "`
else
	TARGET=`ls $INPUT`
fi

for i in $TARGET;do
	echo ""
	echo "OTA: $i"
	build/tools/mk_ota_script/ota $INPUT/$i $OUTPUT/$i $LOGDIR/$i

	if [ ! -z "$MK_OTA_EXTRA" ];then
		mkdir -p $MK_OTA_EXTRA/$TYPE/$i
		cp $OUTPUT/$i/* $MK_OTA_EXTRA/$TYPE/$i 2> /dev/null 
	fi
done
