#!/bin/bash
#
# Copyright (C) 2013 The MoKee OpenSource Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

TARGET=($MK_BUILD)
TYPE=$MK_BUILDTYPE
INPUT=out/target/$TYPE
OUTDIR=out/target/OTA/
LOGSDIR=$OUTDIR/logs

ifdef MK_BUILD_PATH
INPUT=$MK_BUILD_PATH
OUTDIR=$MK_BUILD_PATH/OTA
LOGSDIR=$MK_BUILD_PATH/logs
endif

ifdef MK_OTA_TARGET
TARGET=$MK_OTA_TARGET
endif


for i in "${TARGET[@]}";do
	./ota $INPUT/$TYPE/$i $OUTDIR/$TYPE/$i $LOGS/$i
done
